#!/bin/bash

ROOT=`pwd`
v=$1
dest=linux-$v.obj

#rm -rf linux-$v
#rm -rf $dest

if [[ ! -d linux-$v ]]
then
    echo Unpack linux-$v.tar.bz2
    time tar xjf linux-$v.tar.bz2
fi

if [[ ! -d $dest ]]
then
    mkdir $dest
fi

cd linux-$v
echo ">>>>>>>>>> Cleaning..."
make mrproper
echo ">>>>>>>>>> Configuring..."
#make allnoconfig
make allmodconfig
echo ">>>>>>>>>> Preparing..."
make prepare
cat $ROOT/config | while read line
do
    f=`echo $line | cut -d ' ' -f 1`
    d=`echo $line | cut -d ' ' -f 2`
    if [[ ! -f ../$dest/$f ]]
    then
	if [[ -d fs/$d ]]
	then
	    echo ">>>>>>>>>> Building $f (1st attempt)..."
	    make fs/$d/`basename $f .o`.ko
	    if [ -a  fs/$d/$f ]
	    then
		cp -a fs/$d/$f ../$dest
	    else
		echo ">>>>>>>>>> Building $f (2nd attempt)..."
		make fs/$d/`basename $f .o`.ko `echo $line | cut -d ' ' -f 3-`
		cp -a fs/$d/$f ../$dest
	    fi
	else
	    echo ">>>>>>>>>> Skip $f (missing directory)"
	fi
    else
	echo ">>>>>>>>>> Skip $f (already exists)"
    fi
done
cd ..
